2025-09-29 12:48:09,430 - distributed.nanny - INFO -         Start Nanny at: 'tcp://192.168.86.107:36157'
2025-09-29 12:48:10,296 - distributed.diskutils - INFO - Found stale lock file and directory '/home1/zrentala/dask-worker-space/dask-scratch-space/worker-w7dq3qdg', purging
2025-09-29 12:48:10,775 - distributed.worker - INFO -       Start worker at: tcp://192.168.86.107:41997
2025-09-29 12:48:10,775 - distributed.worker - INFO -          Listening to: tcp://192.168.86.107:41997
2025-09-29 12:48:10,775 - distributed.worker - INFO -           Worker name:             SLURMCluster-0
2025-09-29 12:48:10,775 - distributed.worker - INFO -          dashboard at:       192.168.86.107:36262
2025-09-29 12:48:10,775 - distributed.worker - INFO - Waiting to connect to: tcp://192.168.86.101:41007
2025-09-29 12:48:10,775 - distributed.worker - INFO - -------------------------------------------------
2025-09-29 12:48:10,775 - distributed.worker - INFO -               Threads:                          1
2025-09-29 12:48:10,775 - distributed.worker - INFO -                Memory:                   9.31 GiB
2025-09-29 12:48:10,775 - distributed.worker - INFO -       Local Directory: /home1/zrentala/dask-worker-space/dask-scratch-space/worker-8r6byq5g
2025-09-29 12:48:10,775 - distributed.worker - INFO - -------------------------------------------------
2025-09-29 12:48:11,102 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-09-29 12:48:11,102 - distributed.worker - INFO -         Registered to: tcp://192.168.86.101:41007
2025-09-29 12:48:11,102 - distributed.worker - INFO - -------------------------------------------------
2025-09-29 12:48:11,103 - distributed.core - INFO - Starting established connection to tcp://192.168.86.101:41007
[I 2025-09-29 12:48:11,192] A new study created in memory with name: no-name-0f80cb06-6dc4-4e0d-9f86-bd920f111f81
2025-09-29 12:48:11,210 - distributed.worker - WARNING - Compute Failed
Key:       optimize_subject-1199f460-07a9-4fa6-a04f-8be51ba57442
Function:  execute_task
args:      ((<function optimize_subject at 0x2b7341f38180>, 'Optimization_Results', 'LTP564', (<class 'dict'>, [['LTP564', (<class 'dict'>, [['recall_rate', 0.6644628099173554], ['first_recall', array([0.04878049, 0.07317073, 0.02439024, 0.07317073, 0.07317073,
       0.02439024, 0.02439024, 0.04878049, 0.        , 0.        ,
       0.02439024, 0.02439024, 0.        , 0.14634146, 0.41463415])], ['lag_crp', array([0.10714286, 0.02173913, 0.07936508, 0.15068493, 0.07058824,
       0.09183673, 0.1       , 0.06015038, 0.10958904, 0.11038961,
       0.09302326, 0.08095238, 0.11627907, 0.13807531, 0.        ,
       0.17596567, 0.12037037, 0.11578947, 0.0974359 , 0.11176471,
       0.05063291, 0.11764706, 0.06034483, 0.10576923, 0.07608696,
       0.05882353, 0.        , 0.03448276, 0.11111111])]])], ['LTP565', (<class 'dict'>, [['recall_rate', 0.7995337995337995], ['first_recall', array([0.5       , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ,
kwargs:    {}
Exception: 'NameError("name \'sub_id\' is not defined")'

[I 2025-09-29 12:48:11,211] A new study created in memory with name: no-name-e085bdee-6721-4643-8ec8-364dec2746d9
2025-09-29 12:48:11,228 - distributed.worker - WARNING - Compute Failed
Key:       optimize_subject-0f53a476-d6d7-4ea5-99f6-c925d9888b8c
Function:  execute_task
args:      ((<function optimize_subject at 0x2b734232d8a0>, 'Optimization_Results', 'LTP598', (<class 'dict'>, [['LTP564', (<class 'dict'>, [['recall_rate', 0.6644628099173554], ['first_recall', array([0.04878049, 0.07317073, 0.02439024, 0.07317073, 0.07317073,
       0.02439024, 0.02439024, 0.04878049, 0.        , 0.        ,
       0.02439024, 0.02439024, 0.        , 0.14634146, 0.41463415])], ['lag_crp', array([0.10714286, 0.02173913, 0.07936508, 0.15068493, 0.07058824,
       0.09183673, 0.1       , 0.06015038, 0.10958904, 0.11038961,
       0.09302326, 0.08095238, 0.11627907, 0.13807531, 0.        ,
       0.17596567, 0.12037037, 0.11578947, 0.0974359 , 0.11176471,
       0.05063291, 0.11764706, 0.06034483, 0.10576923, 0.07608696,
       0.05882353, 0.        , 0.03448276, 0.11111111])]])], ['LTP565', (<class 'dict'>, [['recall_rate', 0.7995337995337995], ['first_recall', array([0.5       , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ,
kwargs:    {}
Exception: 'NameError("name \'sub_id\' is not defined")'

[I 2025-09-29 12:48:11,231] A new study created in memory with name: no-name-0f0797de-3cf1-41e9-8ffc-3c04cb6f65ba
2025-09-29 12:48:11,246 - distributed.worker - WARNING - Compute Failed
Key:       optimize_subject-14266715-4132-412d-bef8-f7ce2b95c9a1
Function:  execute_task
args:      ((<function optimize_subject at 0x2b73423acea0>, 'Optimization_Results', 'LTP599', (<class 'dict'>, [['LTP564', (<class 'dict'>, [['recall_rate', 0.6644628099173554], ['first_recall', array([0.04878049, 0.07317073, 0.02439024, 0.07317073, 0.07317073,
       0.02439024, 0.02439024, 0.04878049, 0.        , 0.        ,
       0.02439024, 0.02439024, 0.        , 0.14634146, 0.41463415])], ['lag_crp', array([0.10714286, 0.02173913, 0.07936508, 0.15068493, 0.07058824,
       0.09183673, 0.1       , 0.06015038, 0.10958904, 0.11038961,
       0.09302326, 0.08095238, 0.11627907, 0.13807531, 0.        ,
       0.17596567, 0.12037037, 0.11578947, 0.0974359 , 0.11176471,
       0.05063291, 0.11764706, 0.06034483, 0.10576923, 0.07608696,
       0.05882353, 0.        , 0.03448276, 0.11111111])]])], ['LTP565', (<class 'dict'>, [['recall_rate', 0.7995337995337995], ['first_recall', array([0.5       , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ,
kwargs:    {}
Exception: 'NameError("name \'sub_id\' is not defined")'

[I 2025-09-29 12:48:11,302] A new study created in memory with name: no-name-02111e00-c487-4810-b5ab-fba3453b6f07
2025-09-29 12:48:11,318 - distributed.worker - WARNING - Compute Failed
Key:       optimize_subject-202c9276-3240-4599-8189-9c057d8778a1
Function:  execute_task
args:      ((<function optimize_subject at 0x2b73423ad120>, 'Optimization_Results', 'LTP604', (<class 'dict'>, [['LTP564', (<class 'dict'>, [['recall_rate', 0.6644628099173554], ['first_recall', array([0.04878049, 0.07317073, 0.02439024, 0.07317073, 0.07317073,
       0.02439024, 0.02439024, 0.04878049, 0.        , 0.        ,
       0.02439024, 0.02439024, 0.        , 0.14634146, 0.41463415])], ['lag_crp', array([0.10714286, 0.02173913, 0.07936508, 0.15068493, 0.07058824,
       0.09183673, 0.1       , 0.06015038, 0.10958904, 0.11038961,
       0.09302326, 0.08095238, 0.11627907, 0.13807531, 0.        ,
       0.17596567, 0.12037037, 0.11578947, 0.0974359 , 0.11176471,
       0.05063291, 0.11764706, 0.06034483, 0.10576923, 0.07608696,
       0.05882353, 0.        , 0.03448276, 0.11111111])]])], ['LTP565', (<class 'dict'>, [['recall_rate', 0.7995337995337995], ['first_recall', array([0.5       , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ,
kwargs:    {}
Exception: 'NameError("name \'sub_id\' is not defined")'

2025-09-29 12:48:13,636 - distributed.worker - INFO - Stopping worker at tcp://192.168.86.107:41997. Reason: scheduler-remove-worker
2025-09-29 12:48:13,639 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://192.168.86.107:36157'. Reason: scheduler-remove-worker
2025-09-29 12:48:13,644 - distributed.nanny - INFO - Worker closed
2025-09-29 12:48:13,644 - distributed.core - INFO - Connection to tcp://192.168.86.101:41007 has been closed.
slurmstepd: error: *** JOB 3081168 ON node07 CANCELLED AT 2025-09-29T12:48:13 ***
